# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

course1  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course2  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course3  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course4  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course5  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course6  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course7  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course8  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course9  = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])
course10 = Course.create(title: "", instructor: "", description: "", studio_id: , category_tags: [])

customer1  = Customer.create(name: "")
customer2  = Customer.create(name: "")
customer3  = Customer.create(name: "")
customer4  = Customer.create(name: "")
customer5  = Customer.create(name: "")
customer6  = Customer.create(name: "")
customer7  = Customer.create(name: "")
customer8  = Customer.create(name: "")
customer9  = Customer.create(name: "")
customer10 = Customer.create(name: "")

studio1  = Studio.create(name: "", address: "")
studio2  = Studio.create(name: "", address: "")
studio3  = Studio.create(name: "", address: "")
studio4  = Studio.create(name: "", address: "")
studio5  = Studio.create(name: "", address: "")
studio6  = Studio.create(name: "", address: "")
studio7  = Studio.create(name: "", address: "")
studio8  = Studio.create(name: "", address: "")
studio9  = Studio.create(name: "", address: "")
studio10 = Studio.create(name: "", address: "")

registration1  = Registration.create(customer_id: 1, course_id: 4)
registration2  = Registration.create(customer_id: 2, course_id: 1)
registration3  = Registration.create(customer_id: 3, course_id: 2)
registration4  = Registration.create(customer_id: 4, course_id: 3)
registration5  = Registration.create(customer_id: 5, course_id: 3)
registration6  = Registration.create(customer_id: 6, course_id: 7)
registration7  = Registration.create(customer_id: 7, course_id: 8)
registration8  = Registration.create(customer_id: 8, course_id: 9)
registration9  = Registration.create(customer_id: 9, course_id: 10)
registration10 = Registration.create(customer_id: 8, course_id: 5)

schedule1  = Schedule.create(start_date: "11 July 2016", number_of_weeks: 5, day_of_week: "Monday", time: 05:00, course_id: 1)
schedule2  = Schedule.create(start_date: "05 July 2016", number_of_weeks: 6, day_of_week: "Tuesday", time: 08:00, course_id: 2)
schedule3  = Schedule.create(start_date: "13 July 2016", number_of_weeks: 6, day_of_week: "Wednesday", time: 07:00, course_id: 3)
schedule4  = Schedule.create(start_date: "21 July 2016", number_of_weeks: 8, day_of_week: "Thursday", time: 07:00, course_id: 4)
schedule5  = Schedule.create(start_date: "01 July 2016", number_of_weeks: 5, day_of_week: "Friday", time: 06:00, course_id: 5)
schedule6  = Schedule.create(start_date: "09 July 2016", number_of_weeks: 4, day_of_week: "Saturday", time: 08:00, course_id: 6)
schedule7  = Schedule.create(start_date: "17 July 2016", number_of_weeks: 4, day_of_week: "Sunday", time: 05:30, course_id: 7)
schedule8  = Schedule.create(start_date: "22 June 2016", number_of_weeks: 6, day_of_week: "Wednesday", time: 09:00, course_id: 8)
schedule9  = Schedule.create(start_date: "29 June 2016", number_of_weeks: 8, day_of_week: "Wednesday", time: 06:00, course_id: 9)
schedule10 = Schedule.create(start_date: "11 July 2016", number_of_weeks: 8, day_of_week: "Monday", time: 08:00, course_id: 10)
