# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

course1  = Course.create(title: "Spinning with Carl", instructor: "Carl Sanders", description: "Carl pushes your limits where spinning meets thrill ride status!", studio_id: 10, category_tags: ["cardio", "spin"])
course2  = Course.create(title: "Rock Climbing", instructor: "Steven Nunez", description: "Climb higher than you've ever climbed before, while working off that cronut you ate this morning.", studio_id: 2, category_tags: ["adventure", "strength-training"])
course3  = Course.create(title: "30/60/90", instructor: "Maggie Smith", description: "It doesn't get more intense than this. The Dame herself will lead you in this class, but simply by staring disapprovingly. If you have self-esteem issues, please avoid.", studio_id: 1, category_tags: ["cardio", "strength-training", "high intensity"])
course4  = Course.create(title: "Master Class: One Pose", instructor: "Maharishi Mahesh", description: "Not for the faint of heart, each week you will hold a single Yoga pose for the entire hour.", studio_id: 3, category_tags: ["yoga", "toning"])
course5  = Course.create(title: "Intro to Bikram Yoga", instructor: "Yogi Bear", description: "Center yourself in this introduction to the classic yoga style. No experience necessary.", studio_id: 4, category_tags: ["yoga", "toning"])
course6  = Course.create(title: "Blink and You'll Miss It", instructor: "Usain Bolt", description: "Try to keep up!", studio_id: 5, category_tags: ["cardio"])
course7  = Course.create(title: "CrossFit is CrossFit", instructor: "L Ron Hubbard", description: "CrossFit...come drink the Kool-Aid", studio_id: 6, category_tags: ["cardio", "strength-training", "douchiness"])
course8  = Course.create(title: "Megaformer", instructor: "", description: "Fifty minutes of heart-pumping, muscle quivering and total body strengthening, lengthening and toning in an inspiring, small-group setting", studio_id: 7, category_tags: ["cardio", "strength-training"])
course9  = Course.create(title: "Move(dance cardio & toning)", instructor: "Cat Deeley", description: "So you think you can dance? Hahaha. Prove it.", studio_id: 8, category_tags: ["dance", "cardio", "toniing"])
course10 = Course.create(title: "Racing for the Gold", instructor: "Tyler Winklevoss", description: "If you wanted to know what it was like to row for Harvard, this is your chance. I went to Harvard.", studio_id: 9, category_tags: ["rowing", "sports", "cardio"])

customer1  = Customer.create(name: "Linus Torvalds")
customer2  = Customer.create(name: "Alan Turing")
customer3  = Customer.create(name: "Ada Lovelace")
customer4  = Customer.create(name: "DHH")
customer5  = Customer.create(name: "Yukihiro Matsumoto")
customer6  = Customer.create(name: "Eli Manning")
customer7  = Customer.create(name: "Odell Beckham Jr.")
customer8  = Customer.create(name: "LeBron James")
customer9  = Customer.create(name: "Lindsey Vonn")
customer10 = Customer.create(name: "Clint Dempsey")

studio1  = Studio.create(name: "Equinox", address: "14 Wall St, New York, NY 10005")
studio2  = Studio.create(name: "NY Health and Racquet", address: "39 Whitehall St, New York, NY 10004")
studio3  = Studio.create(name: "Yoga to the People", address: "12 St Marks Pl #2R, New York, NY 10003")
studio4  = Studio.create(name: "Pure Yoga East", address: "203 E 86th St, New York, NY 10028")
studio5  = Studio.create(name: "Blink Fitness", address: "107 Nassau St, New York, NY 10038")
studio6  = Studio.create(name: "CrossFit NYC", address: "50 W 28th St, New York, NY 10001")
studio7  = Studio.create(name: "SLT NYC", address: "137 Fifth Avenue, 2nd floor, New York, NY 10010")
studio8  = Studio.create(name: "The Movement Fitness", address: "32 W 18th St, New York, NY 10011")
studio9  = Studio.create(name: "City Row", address: "80 5th Ave #1501, New York, NY 10011")
studio10 = Studio.create(name: "SoulCycle", address: "126 Leroy St, New York, NY 10014")

registration1  = Registration.create(customer_id: 1, course_id: 4)
registration2  = Registration.create(customer_id: 2, course_id: 1)
registration3  = Registration.create(customer_id: 3, course_id: 2)
registration4  = Registration.create(customer_id: 4, course_id: 3)
registration5  = Registration.create(customer_id: 5, course_id: 3)
registration6  = Registration.create(customer_id: 6, course_id: 7)
registration7  = Registration.create(customer_id: 7, course_id: 8)
registration8  = Registration.create(customer_id: 8, course_id: 9)
registration9  = Registration.create(customer_id: 9, course_id: 10)
registration10 = Registration.create(customer_id: 8, course_id: 5)

schedule1  = Schedule.create(start_date: "11 July 2016", number_of_weeks: 5, day_of_week: "Monday", time: +0600, course_id: 1)
schedule2  = Schedule.create(start_date: "05 July 2016", number_of_weeks: 6, day_of_week: "Tuesday", time: +0500, course_id: 2)
schedule3  = Schedule.create(start_date: "13 July 2016", number_of_weeks: 6, day_of_week: "Wednesday", time: +0700, course_id: 3)
schedule4  = Schedule.create(start_date: "21 July 2016", number_of_weeks: 8, day_of_week: "Thursday", time: +0700, course_id: 4)
schedule5  = Schedule.create(start_date: "01 July 2016", number_of_weeks: 5, day_of_week: "Friday", time: +0700, course_id: 5)
schedule6  = Schedule.create(start_date: "09 July 2016", number_of_weeks: 4, day_of_week: "Saturday", time: +0600, course_id: 6)
schedule7  = Schedule.create(start_date: "17 July 2016", number_of_weeks: 4, day_of_week: "Sunday", time: +0600, course_id: 7)
schedule8  = Schedule.create(start_date: "22 June 2016", number_of_weeks: 6, day_of_week: "Wednesday", time: +0600, course_id: 8)
schedule9  = Schedule.create(start_date: "29 June 2016", number_of_weeks: 8, day_of_week: "Wednesday", time: +0600, course_id: 9)
schedule10 = Schedule.create(start_date: "11 July 2016", number_of_weeks: 8, day_of_week: "Monday", time: +0600, course_id: 10)
